---

- name: run restart
  community.docker.docker_container:
    name: "{{ item.name|default(item) }}"
    state: started
    restart: true
  with_items: "{{ docker_run_containers }}"

- name: restart docker
  service:
    name: docker
    state: restarted
